// ─────────────────────────────────────────────────────────────
//  data.js  —  Weekly shift data
//  ⚠️  This is the ONLY file you edit each week.
//  Steps:
//    1. Copy BASE_WEEK1 → BASE_WEEK2
//    2. Replace BASE_WEEK1 with the new week's data
//    3. Update W1_DATES, W2_DATES, W1_LABEL, W2_LABEL in config.js
//    4. Set WEEK2_AVAILABLE = true in config.js when ready
// ─────────────────────────────────────────────────────────────

export const BASE_WEEK1 = [
    {name:'Luces Jessica',      role:'Add. Multiplex',     contract:30, days:[
            {t:'apertura', time:'13:15–19:15', role:'CONC 5',  h:6},
            {t:'apertura',   time:'10:00–16:00', role:'CONC 5',  h:6},
            {t:'assente',    time:'',            role:'',         h:0},
            {t:'off',        time:'',            role:'',         h:0},
            {t:'off',        time:'',            role:'',         h:0},
            {t:'apertura', time:'13:15–19:15', role:'CONC',    h:6},
            {t:'apertura', time:'13:15–19:15', role:'CONC',    h:6},
        ]},
    {name:'Soare Oana',         role:'Add. Maranza',     contract:30, days:[
            {t:'chiusura',   time:'18:45–00:45', role:'LAV 7',   h:6},
            {t:'intermedio',   time:'18:00–00:00', role:'CONC 3',  h:6},
            {t:'apertura',   time:'10:15–16:15', role:'CONC 5',  h:6},
            {t:'chiusura',   time:'17:45–23:45', role:'LAV',     h:6},
            {t:'off',        time:'',            role:'',         h:0},
            {t:'assente',    time:'',            role:'',         h:0},
            {t:'off',        time:'',            role:'',         h:0},
        ]},
    {name:'Gribaudi Jodi',      role:'Add. Multiplex V',   contract:16, days:[
            {t:'off',        time:'',                         role:'',      h:0},
            {t:'intermedio', time:'14:30–23:00', role:'FLOOR', h:8},
            {t:'chiusura',   time:'17:15–01:45', role:'FLOOR', h:8},
            {t:'off',        time:'',                         role:'',      h:0},
            {t:'off',        time:'',                         role:'',      h:0},
            {t:'off',        time:'',                         role:'',      h:0},
            {t:'off',        time:'',                         role:'',      h:0},
        ]},
    {name:'Lo Giudice Luca',    role:'Add. Grande Bluff',  contract:20, days:[
            {t:'intermedio',   time:'17:00–23:00',              role:'FLOOR', h:6},
            {t:'apertura',   time:'10:00–16:00',              role:'FLOOR', h:6},
            {t:'intermedio',   time:'15:30–00:00', role:'FLOOR', h:8},
            {t:'off',        time:'',                         role:'',      h:0},
            {t:'off',        time:'',                         role:'',      h:0},
            {t:'off',        time:'',                         role:'',      h:0},
            {t:'off',        time:'',                         role:'',      h:0},
        ]},
    {name:'Tardugno Juliana',   role:'Add. Multiplex V',   contract:20, days:[
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
        ]},
    {name:'Cancellara Francesco',role:'Add. Goat totale',  contract:20, days:[
            {t:'intermedio',   time:'20:00–00:00', role:'FLOOR', h:4},
            {t:'chiusura',   time:'23:00–03:00', role:'FLOOR', h:4},
            {t:'off',        time:'',            role:'',       h:0},
            {t:'intermedio',   time:'19:00–23:00', role:'FLOOR', h:4},
            {t:'intermedio',   time:'19:00–23:00', role:'FLOOR', h:4},
            {t:'off',        time:'',            role:'',       h:0},
            {t:'intermedio', time:'17:00–21:00', role:'FLOOR', h:4},
        ]},
    {name:'Sereno Federico',    role:'Add. Blu Ray V',     contract:20, days:[
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
        ]},
    {name:'Scarpella Samuele',  role:'Add. Multiplex V',   contract:20, days:[
            {t:'chiusura',   time:'21:00–01:00', role:'CONC 6', h:4},
            {t:'intermedio',   time:'16:15–22:15', role:'FLOOR',  h:6},
            {t:'intermedio',   time:'14:15–18:15', role:'LAV 7',  h:4},
            {t:'off',        time:'',            role:'',        h:0},
            {t:'apertura', time:'13:15–19:15', role:'CONC',   h:6},
            {t:'off',        time:'',            role:'',        h:0},
            {t:'off',        time:'',            role:'',        h:0},
        ]},
    {name:'Improta Dennis',     role:'Add. Multiplex',     contract:20, days:[
            {t:'intermedio', time:'17:15–21:15', role:'CONC 4', h:4},
            {t:'off',        time:'',            role:'',        h:0},
            {t:'apertura',   time:'10:15–14:15', role:'FLOOR',  h:4},
            {t:'chiusura',   time:'20:00–00:00', role:'CONC', h:4},
            {t:'off',        time:'',            role:'',        h:0},
            {t:'intermedio', time:'14:30–18:30', role:'DELIVERY',h:4},
            {t:'chiusura',   time:'20:15–00:15', role:'CONC', h:4},
        ]},
    {name:'Tonetti Simone',     role:'Add. Stracci',     contract:20, days:[
            {t:'off',        time:'',            role:'',        h:0},
            {t:'chiusura',   time:'22:15–02:15', role:'CONC 6', h:4},
            {t:'intermedio', time:'16:00–20:00', role:'CONC 5', h:4},
            {t:'intermedio', time:'16:15–20:15', role:'CONC',   h:4},
            {t:'chiusura',   time:'19:00–23:00', role:'CONC',   h:4},
            {t:'intermedio', time:'18:15–22:15', role:'DELIVERY',h:4},
            {t:'assente',    time:'',            role:'',        h:0},
        ]},
    {name:'Perri Daniel',       role:'Add. MultiSex',      contract:20, days:[
            {t:'apertura',   time:'13:30–17:30', role:'LAV 7',       h:4},
            {t:'intermedio', time:'15:00–19:00', role:'CONC 3/FLOOR', h:4},
            {t:'intermedio',   time:'19:00–23:00', role:'CONC 4',      h:4},
            {t:'off',        time:'',            role:'',             h:0},
            {t:'off',        time:'',            role:'',             h:0},
            {t:'apertura', time:'13:15–17:15', role:'FLOOR',       h:4},
            {t:'intermedio',   time:'19:00–23:00', role:'FLOOR',       h:4},
        ]},
    {name:'Ventrella Mattia',   role:'Add. Multiplex',     contract:20, days:[
            {t:'intermedio',   time:'19:00–23:00', role:'CONC 5', h:4},
            {t:'intermedio', time:'15:00–19:00', role:'CONC 4', h:4},
            {t:'intermedio', time:'15:00–19:00', role:'CONC 4', h:4},
            {t:'intermedio',   time:'19:00–23:00', role:'CONC',   h:4},
            {t:'apertura',   time:'13:30–17:30', role:'LAV',    h:4},
            {t:'off',        time:'',            role:'',        h:0},
            {t:'off',        time:'',            role:'',        h:0},
        ]},
    {name:'Luces Valentina',    role:'Add. Choker',        contract:20, days:[
            {t:'off',        time:'',            role:'',        h:0},
            {t:'chiusura',   time:'22:00–02:00', role:'LAV 7',  h:4},
            {t:'intermedio',   time:'18:00–22:00', role:'CONC 6', h:4},
            {t:'chiusura',   time:'21:00–01:00', role:'FLOOR',  h:4},
            {t:'intermedio',   time:'17:00–21:00', role:'FLOOR',  h:4},
            {t:'intermedio', time:'17:15–21:15', role:'LAV',    h:4},
            {t:'off',        time:'',            role:'',        h:0},
        ]},
    {name:'Martino Lucia',      role:'Add. Multiplex',     contract:20, days:[
            {t:'assente',    time:'',            role:'',        h:0},
            {t:'assente',    time:'',            role:'',        h:0},
            {t:'chiusura',   time:'20:45–00:45', role:'CONC 5', h:4},
            {t:'off',        time:'',            role:'',        h:0},
            {t:'off',        time:'',            role:'',        h:0},
            {t:'chiusura',   time:'19:45–23:45', role:'LAV',    h:4},
            {t:'intermedio',   time:'19:00–23:00', role:'CONC',   h:4},
        ]},
    {name:'Moresco Leonardo',   role:'Add. Multiplex',     contract:20, days:[
            {t:'apertura',   time:'13:15–17:15', role:'FLOOR',      h:4},
            {t:'intermedio',   time:'18:15–22:15', role:'LAV 7',      h:4},
            {t:'off',        time:'',            role:'',            h:0},
            {t:'off',        time:'',            role:'',            h:0},
            {t:'intermedio', time:'15:30–19:30', role:'CONC/FLOOR', h:4},
            {t:'intermedio',   time:'19:00–23:00', role:'CONC',       h:4},
            {t:'intermedio', time:'17:00–21:00', role:'LAV',        h:4},
        ]},
    {name:'Paratore Marco',     role:'Add. Multiplex',     contract:20, days:[
            {t:'off',        time:'',            role:'',       h:0},
            {t:'intermedio',   time:'21:00–01:00', role:'FLOOR', h:4},
            {t:'intermedio',   time:'19:00–23:00', role:'FLOOR', h:4},
            {t:'intermedio',   time:'17:00–21:00', role:'FLOOR', h:4},
            {t:'off',        time:'',            role:'',       h:0},
            {t:'intermedio',   time:'19:00–23:00', role:'FLOOR', h:4},
            {t:'chiusura',   time:'21:15–01:15', role:'FLOOR', h:4},
        ]},
    {name:'Perin Daniele',      role:'Add. Multiplex',     contract:20, days:[
            {t:'assente',    time:'',                         role:'',      h:0},
            {t:'intermedio',   time:'16:15–00:45', role:'CONC 5',h:8},
            {t:'chiusura',   time:'18:30–00:30',              role:'LAV 7', h:6},
            {t:'off',        time:'',                         role:'',      h:0},
            {t:'chiusura',   time:'17:45–23:45',              role:'LAV',   h:6},
            {t:'off',        time:'',                         role:'',      h:0},
            {t:'off',        time:'',                         role:'',      h:0},
        ]},
    {name:'Bogdan Denis',       role:'Add. Fortnite',      contract:20, days:[
            {t:'off',        time:'',            role:'',           h:0},
            {t:'intermedio',   time:'10:30–14:30', role:'CONC/FLOOR', h:4},
            {t:'intermedio', time:'16:15–20:15', role:'CONC 3',    h:4},
            {t:'apertura',   time:'13:15–17:15', role:'FLOOR',     h:4},
            {t:'off',        time:'',            role:'',           h:0},
            {t:'apertura',   time:'13:30–17:30', role:'LAV',       h:4},
            {t:'intermedio',   time:'13:15–17:15', role:'FLOOR',     h:4},
        ]},
    {name:'Chouhadi Sara',      role:'Add. Multiplex',     contract:20, days:[
            {t:'off',        time:'',            role:'',           h:0},
            {t:'apertura',   time:'10:30–14:30', role:'LAV 7',     h:4},
            {t:'intermedio',   time:'20:00–00:00', role:'CONC 3',    h:4},
            {t:'intermedio', time:'15:30–19:30', role:'CONC/FLOOR', h:4},
            {t:'off',        time:'',            role:'',           h:0},
            {t:'chiusura',   time:'20:00–00:00', role:'CONC',      h:4},
            {t:'apertura',   time:'13:30–17:30', role:'LAV',       h:4},
        ]},
    {name:'El Fadili Rim',      role:'Add. Multiplex',     contract:20, days:[
            {t:'off',        time:'',            role:'',                  h:0},
            {t:'intermedio',   time:'19:00–23:00', role:'CONC 2',           h:4},
            {t:'intermedio', time:'15:00–19:00', role:'CONC 2/FLOOR',     h:4},
            {t:'apertura',   time:'13:15–17:15', role:'CONC',             h:4},
            {t:'chiusura',   time:'20:00–00:00', role:'CONC/MILKSHAKE ??? GIRL SHAKE THAT MILK',   h:4},
            {t:'intermedio', time:'17:00–21:00', role:'FLOOR',            h:4},
            {t:'off',        time:'',            role:'',                  h:0},
        ]},
    {name:'Farag Fabio Bishoy', role:'Add. Multiplex',     contract:20, days:[
            {t:'intermedio', time:'16:00–20:00', role:'FLOOR/CONC 3', h:4},
            {t:'intermedio', time:'14:30–18:30', role:'LAV 7',        h:4},
            {t:'apertura',   time:'10:30–14:30', role:'LAV 7',        h:4},
            {t:'off',        time:'',            role:'',              h:0},
            {t:'chiusura',   time:'21:00–01:00', role:'FLOOR',        h:4},
            {t:'off',        time:'',            role:'',              h:0},
            {t:'chiusura',   time:'20:00–00:00', role:'LAV',          h:4},
        ]},
    {name:'Corvino Niccolò',    role:'Add. Multiplex',     contract:20, days:[
            {t:'chiusura',   time:'22:00–02:00', role:'FLOOR', h:4},
            {t:'intermedio', time:'17:00–21:00', role:'FLOOR', h:4},
            {t:'intermedio',   time:'14:00–18:00', role:'FLOOR', h:4},
            {t:'off',        time:'',            role:'',       h:0},
            {t:'apertura',   time:'13:15–17:15', role:'FLOOR', h:4},
            {t:'chiusura',   time:'21:00–01:00', role:'FLOOR', h:4},
            {t:'off',        time:'',            role:'',       h:0},
        ]},
];

export const BASE_WEEK2 = [
    {name:'Luces Jessica',      role:'Add. Multiplex',     contract:30, days:[
            {t:'apertura', time:'13:15–19:15', role:'CONC 5',  h:6},
            {t:'apertura',   time:'10:00–16:00', role:'CONC 5',  h:6},
            {t:'intermedio', time:'14:00–20:00', role:'CONC 4',  h:6},
            {t:'off',        time:'',            role:'',         h:0},
            {t:'off',        time:'',            role:'',         h:0},
            {t:'apertura', time:'13:15–19:15', role:'CONC',    h:6},
            {t:'apertura', time:'13:15–19:15', role:'CONC',    h:6},
        ]},
    {name:'Soare Oana',         role:'Add. Multiplex',     contract:30, days:[
            {t:'chiusura',   time:'19:15–01:15', role:'CONC 5',  h:6},
            {t:'intermedio', time:'17:00–23:00', role:'FLOOR',   h:6},
            {t:'apertura',   time:'10:15–16:15', role:'FLOOR',   h:6},
            {t:'off',        time:'',            role:'',         h:0},
            {t:'off',        time:'',            role:'',         h:0},
            {t:'chiusura',   time:'18:00–00:00', role:'LAV',     h:6},
            {t:'intermedio', time:'17:00–23:00', role:'FLOOR',   h:6},
        ]},
    {name:'Gribaudi Jodi',      role:'Add. Multiplex V',   contract:16, days:[
            {t:'off',     time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'off',     time:'', role:'', h:0},
            {t:'off',     time:'', role:'', h:0},
            {t:'off',     time:'', role:'', h:0},
            {t:'off',     time:'', role:'', h:0},
        ]},
    {name:'Lo Giudice Luca',    role:'Add. Grande Bluff',  contract:20, days:[
            {t:'chiusura',   time:'20:15–02:15',              role:'FLOOR', h:6},
            {t:'intermedio', time:'14:30–23:00', role:'FLOOR', h:8},
            {t:'intermedio',   time:'18:00–00:00',              role:'FLOOR', h:6},
            {t:'off',        time:'',                         role:'',      h:0},
            {t:'off',        time:'',                         role:'',      h:0},
            {t:'off',        time:'',                         role:'',      h:0},
            {t:'off',        time:'',                         role:'',      h:0},
        ]},
    {name:'Tardugno Juliana',   role:'Add. Multiplex V',   contract:20, days:[
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
        ]},
    {name:'Cancellara Francesco',role:'Add. Goat totale',  contract:20, days:[
            {t:'intermedio',   time:'20:00–00:00', role:'FLOOR', h:4},
            {t:'intermedio',   time:'21:00–01:00', role:'FLOOR', h:4},
            {t:'off',        time:'',            role:'',       h:0},
            {t:'chiusura',   time:'21:15–01:15', role:'FLOOR', h:4},
            {t:'intermedio',   time:'19:00–23:00', role:'FLOOR', h:4},
            {t:'off',        time:'',            role:'',       h:0},
            {t:'intermedio',   time:'19:00–23:00', role:'FLOOR', h:4},
        ]},
    {name:'Sereno Federico',    role:'Add. Blu Ray V',     contract:20, days:[
            {t:'assente',    time:'',            role:'',      h:0},
            {t:'chiusura',   time:'21:00–02:00', role:'LAV 7', h:5},
            {t:'chiusura',   time:'19:00–01:00', role:'LAV 7', h:6},
            {t:'off',        time:'',            role:'',       h:0},
            {t:'off',        time:'',            role:'',       h:0},
            {t:'intermedio', time:'17:30–22:30', role:'CONC',  h:5},
            {t:'intermedio', time:'17:00–21:00', role:'CONC',  h:4},
        ]},
    {name:'Scarpella Samuele',  role:'Add. Multiplex V',   contract:20, days:[
            {t:'apertura',   time:'13:30–17:30', role:'LAV 7', h:4},
            {t:'intermedio',   time:'18:00–22:00', role:'CONC 6',h:4},
            {t:'off',        time:'',            role:'',       h:0},
            {t:'intermedio', time:'15:00–19:00', role:'CONC',  h:4},
            {t:'intermedio', time:'17:00–21:00', role:'FLOOR', h:4},
            {t:'off',        time:'',            role:'',       h:0},
            {t:'apertura',   time:'13:15–17:15', role:'FLOOR', h:4},
        ]},
    {name:'Improta Dennis',     role:'Add. Multiplex',     contract:20, days:[
            {t:'intermedio',   time:'19:00–23:00',              role:'CONC 4', h:4},
            {t:'apertura',   time:'10:00–14:00',              role:'FLOOR',  h:4},
            {t:'intermedio', time:'14:00–22:30', role:'CONC 5', h:8},
            {t:'off',        time:'',                         role:'',        h:0},
            {t:'chiusura',   time:'20:00–00:00',              role:'LAV',    h:4},
            {t:'off',        time:'',                         role:'',        h:0},
            {t:'off',        time:'',                         role:'',        h:0},
        ]},
    {name:'Tonetti Simone',     role:'Add. Multiplex',     contract:20, days:[
            {t:'off',        time:'',            role:'',       h:0},
            {t:'intermedio',   time:'20:45–00:45', role:'CONC 4', h:4},
            {t:'off',        time:'',            role:'',        h:0},
            {t:'intermedio', time:'17:00–21:00', role:'CONC',   h:4},
            {t:'chiusura',   time:'20:15–00:15', role:'CONC',   h:4},
            {t:'apertura',   time:'13:30–17:30', role:'LAV',    h:4},
            {t:'intermedio',   time:'19:00–23:00', role:'CONC',   h:4},
        ]},
    {name:'Perri Daniel',       role:'Add. MultiSex',      contract:20, days:[
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
            {t:'assente', time:'', role:'', h:0},
        ]},
    {name:'Ventrella Mattia',   role:'Add. Multiplex',     contract:20, days:[
            {t:'intermedio', time:'17:15–21:15',              role:'LAV 7',  h:4},
            {t:'intermedio',   time:'20:00–00:00',              role:'CONC 5', h:4},
            {t:'intermedio',   time:'19:30–23:30',              role:'CONC 6', h:4},
            {t:'off',        time:'',                         role:'',        h:0},
            {t:'off',        time:'',                         role:'',        h:0},
            {t:'off',        time:'',                         role:'',        h:0},
            {t:'chiusura',   time:'15:30–00:00', role:'LAV',    h:8},
        ]},
    {name:'Luces Valentina',    role:'Add. Choker',        contract:20, days:[
            {t:'off',        time:'',            role:'',            h:0},
            {t:'chiusura',   time:'22:15–02:15', role:'CONC 6',     h:4},
            {t:'intermedio',   time:'19:00–23:00', role:'FLOOR',      h:4},
            {t:'apertura',   time:'13:15–17:15', role:'CONC',       h:4},
            {t:'intermedio', time:'16:00–20:00', role:'LAV',        h:4},
            {t:'intermedio',   time:'19:15–23:15', role:'CONC/FLOOR', h:4},
            {t:'off',        time:'',            role:'',            h:0},
        ]},
    {name:'Martino Lucia',      role:'Add. Multiplex',     contract:20, days:[
            {t:'chiusura',   time:'21:00–01:00', role:'LAV 7',  h:4},
            {t:'intermedio', time:'16:00–20:00', role:'CONC 5', h:4},
            {t:'apertura',   time:'10:15–14:15', role:'CONC 5', h:4},
            {t:'off',        time:'',            role:'',        h:0},
            {t:'off',        time:'',            role:'',        h:0},
            {t:'intermedio',   time:'19:00–23:00', role:'CONC',   h:4},
            {t:'chiusura',   time:'20:15–00:15', role:'CONC',   h:4},
        ]},
    {name:'Moresco Leonardo',   role:'Add. Multiplex',     contract:20, days:[
            {t:'off',        time:'',            role:'',            h:0},
            {t:'intermedio',   time:'13:45–17:45', role:'FLOOR',      h:4},
            {t:'chiusura',   time:'21:15–01:15', role:'CONC 4',     h:4},
            {t:'intermedio',   time:'19:00–23:00', role:'CONC',       h:4},
            {t:'intermedio', time:'15:00–19:00', role:'CONC/FLOOR', h:4},
            {t:'off',        time:'',            role:'',            h:0},
            {t:'chiusura',   time:'21:15–01:15', role:'FLOOR',      h:4},
        ]},
    {name:'Paratore Marco',     role:'Add. Multiplex',     contract:20, days:[
            {t:'off',        time:'',            role:'',       h:0},
            {t:'assente',    time:'',            role:'',       h:0},
            {t:'chiusura',   time:'22:15–02:15', role:'FLOOR', h:4},
            {t:'intermedio',   time:'19:00–23:00', role:'FLOOR', h:4},
            {t:'apertura',   time:'13:15–17:15', role:'FLOOR', h:4},
            {t:'apertura',   time:'13:15–17:15', role:'FLOOR', h:4},
            {t:'off',        time:'',            role:'',       h:0},
        ]},
    {name:'Perin Daniele',      role:'Add. Multiplex',     contract:20, days:[
            {t:'off',        time:'',                         role:'',       h:0},
            {t:'intermedio', time:'15:00–21:00',              role:'LAV 7',  h:6},
            {t:'apertura',   time:'10:30–19:00', role:'LAV 7',  h:8},
            {t:'chiusura',   time:'18:00–00:00',              role:'LAV',    h:6},
            {t:'off',        time:'',                         role:'',       h:0},
            {t:'off',        time:'',                         role:'',       h:0},
            {t:'off',        time:'',                         role:'',       h:0},
        ]},
    {name:'Bogdan Denis',       role:'Add. Fortnite',      contract:20, days:[
            {t:'off',        time:'',            role:'',       h:0},
            {t:'chiusura',   time:'23:15–03:15', role:'FLOOR', h:4},
            {t:'intermedio', time:'15:00–19:00', role:'CONC 3', h:4},
            {t:'intermedio', time:'17:00–21:00', role:'FLOOR', h:4},
            {t:'intermedio',   time:'19:00–23:00', role:'CONC',  h:4},
            {t:'intermedio', time:'17:00–21:00', role:'FLOOR', h:4},
            {t:'off',        time:'',            role:'',       h:0},
        ]},
    {name:'Chouhadi Sara',      role:'Add. Multiplex',     contract:20, days:[
            {t:'off',        time:'',            role:'',            h:0},
            {t:'intermedio',   time:'10:30–14:30', role:'CONC 4',     h:4},
            {t:'intermedio', time:'16:00–20:00', role:'CONC 2/FLOOR',h:4},
            {t:'chiusura',   time:'20:15–00:15', role:'CONC',       h:4},
            {t:'apertura',   time:'13:15–17:15', role:'CONC',       h:4},
            {t:'intermedio',   time:'19:00–23:00', role:'FLOOR',      h:4},
            {t:'off',        time:'',            role:'',            h:0},
        ]},
    {name:'El Fadili Rim',      role:'Add. Multiplex',     contract:20, days:[
            {t:'intermedio', time:'17:00–21:00', role:'FLOOR',  h:4},
            {t:'apertura',   time:'11:00–15:00', role:'LAV 7',  h:4},
            {t:'intermedio', time:'15:15–19:15', role:'FLOOR',  h:4},
            {t:'apertura',   time:'13:15–17:15', role:'FLOOR',  h:4},
            {t:'off',        time:'',            role:'',        h:0},
            {t:'chiusura',   time:'20:15–00:15', role:'CONC',   h:4},
            {t:'off',        time:'',            role:'',        h:0},
        ]},
    {name:'Farag Fabio Bishoy', role:'Add. Multiplex',     contract:20, days:[
            {t:'off',        time:'',            role:'',        h:0},
            {t:'intermedio', time:'14:30–20:30', role:'CONC 4', h:6},
            {t:'intermedio', time:'14:00–18:00', role:'FLOOR',  h:4},
            {t:'off',        time:'',            role:'',        h:0},
            {t:'chiusura',   time:'21:15–01:15', role:'FLOOR',  h:4},
            {t:'chiusura',   time:'19:15–01:15', role:'FLOOR',  h:6},
            {t:'off',        time:'',            role:'',        h:0},
        ]},
    {name:'Corvino Niccolò',    role:'Add. Multiplex',     contract:20, days:[
            {t:'apertura',   time:'13:15–17:15', role:'FLOOR', h:4},
            {t:'assente',    time:'',            role:'',       h:0},
            {t:'assente',    time:'',            role:'',       h:0},
            {t:'off',        time:'',            role:'',       h:0},
            {t:'off',        time:'',            role:'',       h:0},
            {t:'assente',    time:'',            role:'',       h:0},
            {t:'assente',    time:'',            role:'',       h:0},
        ]},
];
